### ISSUE TITLE
Training-LDMI Code

### ISSUE THREAD

**Issue by mrodda117** [serdarozsoy/corinfomax-ssl#2]
Hi,
Firstly great paper and code! Was really easy to implement and get running straight away.

For supplementary section L comparing the Training-LDMI, I had a dig around and couldn't find any reference to this in the repo - have I missed something obvious? If not, are you able to provide the code to calculate the training-LDMI?
![image](https://user-images.githubusercontent.com/37528090/204922460-89318efe-fdeb-497d-a6e1-b15b4df720f3.png)

Thanks!

**Comment by serdarozsoy** [comment]
Thank you for your interest and positive feedback. 

No, you haven’t missed anything obvious. We didn’t include the related code part in this repository to prevent any confusion, because we use only CorInfoMax as a loss for our experiments. So that example with LDMI loss in the supplementary part was only for the tracking purpose.

In any case, I would like to share the LDMI tracking code as supplementary in the “extras” folder. So, you can find how it is done by this link:

https://github.com/serdarozsoy/corinfomax-ssl/tree/main/extras/ldmi_plot

**Comment by serdarozsoy** [comment]
This issue was closed as it has not been active for 2 months since the last reply.
